version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - git submodule update --init --recursive
    post_build:
      - sphinx-build -b latexpdf docs docs/_build/pdf

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

search:
  ranking:
    api.html: 5
    setup.html: 3
    architecture.html: 2

submodules:
  include: all
  recursive: true
